services:
  backend:
    build: ./api
    ports:
      - 3100:3100
    volumes:
      - test-v:/storage
  frontend:
    build: ./web
    ports:
      - 3200:3200
    environment:
      - api=http://backend:3100
volumes:
  test-v: